name: Price Tracker

on:
  schedule:
    - cron: "0 * * * *"  # 每小時
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run script
        run: python tracker.py
